//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhmK22CNT3Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhmAccount
    {
        public int NhmID { get; set; }
        public string NhmUserName { get; set; }
        public string NhmPassword { get; set; }
        public string NhmFullName { get; set; }
        public string NhmEmail { get; set; }
        public string NhmPhone { get; set; }
        public Nullable<bool> NhmActive { get; set; }
    }
}
